import React, { useContext, useEffect } from "react"
import * as S from "./privacy.css"

const Privacy = () => {
  return (
    <>


      <S.Wrapper>
      <S.Overlay></S.Overlay>
        <S.StyledTitle>
          <S.H1>Privacy Policy</S.H1>
        </S.StyledTitle>
        <S.StyledArticle>
          <S.StyledDiv>
            <S.P>
              Effective date: March 26, 2019 My CBD Lab LLC (“us”, “we”, or
              “our”) operates the <S.A>http://hempup.com</S.A> website (hereinafter
              referred to as the “Service”). This page informs you of our
              policies regarding the collection, use and disclosure of personal
              data when you use our Service and the choices you have associated
              with that data. We use your data to provide and improve the
              Service. By using the Service, you agree to the collection and use
              of information in accordance with this policy. Unless otherwise
              defined in this Privacy Policy, the terms used in this Privacy
              Policy have the same meanings as in our Terms and Conditions,
              accessible from <S.A>http://hempup.com</S.A>.
            </S.P>
          </S.StyledDiv>
          <S.StyledDiv>
            <S.H2>Definitions</S.H2>
            <S.UL>
              <li>
                <S.Title>Service</S.Title>
                Service is the http://hempup.com website operated by Hemp UP LLC
              </li>
              <li>
                <S.Title>Personal Data</S.Title>
                Personal Data means data about a living individual who can be
                identified from those data (or from those and other information
                either in our possession or likely to come into our possession).
              </li>
              <li>
                <S.Title>Usage Data</S.Title>
                Usage Data is data collected automatically either generated by
                the use of the Service or from the Service infrastructure itself
                (for example, the duration of a page visit).
              </li>
              <li>
                <S.Title>Cookies</S.Title>
                Cookies are small files stored on your device (computer or
                mobile device).
              </li>
            </S.UL>
          </S.StyledDiv>


          <S.StyledDiv>
          <S.H2>Information Collection and Use</S.H2>
            <S.P>
            We collect several different types of information for various purposes to provide and improve our Service to you.
            </S.P>
          </S.StyledDiv>

          <S.StyledDiv>
          <S.H2>Types of Data Collected</S.H2>
          <S.Title>Personal Data</S.Title>
            <S.P>
            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
            </S.P>
            <S.UL>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Cookies and Usage Data</li>
            </S.UL>
            <S.P>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</S.P>
          </S.StyledDiv>

          <S.StyledDiv>
          <S.Title>Usage Data</S.Title>
            <S.P>
            We may also collect information on how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </S.P>
          </S.StyledDiv>

          <S.StyledDiv>
          <S.Title>Tracking & Cookies Data</S.Title>
            <S.P>
            We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
            </S.P>
            <S.P>
            Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
            </S.P>
            <S.P>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
            </S.P>
            <S.P>
            Examples of Cookies we use:
            </S.P>
            <S.UL>
                <li><S.Title>Session Cookies</S.Title>We use Session Cookies to operate our Service.
                </li>
                <li><S.Title>Preference Cookies</S.Title>We use Preference Cookies to remember your preferences and various settings.
                </li>
                <li><S.Title>Security Cookies</S.Title>We use Security Cookies for security purposes.
                </li>
            </S.UL>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Use of Data</S.H2>
            <S.P>
            My CBD Lab LLC uses the collected data for various purposes:
            </S.P>
            <S.UL>
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide customer support</li>
                <li>To gather analysis or valuable information so that we can improve our Service</li>
                <li>To monitor the usage of our Service</li>
                <li>To detect, prevent and address technical issues</li>
                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
            </S.UL>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Transfer of Data</S.H2>
            <S.P>
            Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
            </S.P>
            <S.P>If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</S.P>
            <S.P>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</S.P>
            <S.P>Hemp UP LLC will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</S.P>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Disclosure of Data
Legal Requirements</S.H2>
            <S.P> 
            My CBD Lab LLC may disclose your Personal Data in the good faith belief that such action is necessary to:
              <S.ContactWrap>
                <S.UL >
                  <li>
                  To comply with a legal obligation
                  </li>
                  <li>
                  To protect and defend the rights or property of Hemp Up LLC
                  </li>
                  <li>
                  To prevent or investigate possible wrongdoing in connection with the Service
                  </li>
                  <li>
                  To protect the personal safety of users of the Service or the public
                  </li>
                  <li>
                  To protect against legal liability
                  </li>
                </S.UL>
              </S.ContactWrap>
            </S.P>
          </S.StyledDiv>


          <S.StyledDiv>
              <S.H2>Security of Data</S.H2>
            <S.P>
            The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
            </S.P>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Service Providers</S.H2>
            <S.P>
            We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
            </S.P>
            <S.P>
            These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
            </S.P>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Analytics</S.H2>
            <S.P>
            We may use third-party Service Providers to monitor and analyse the use of our Service.
            </S.P>
            <S.UL>
                <li><S.Title>Google Analytics</S.Title>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <S.A>https://policies.google.com/privacy?hl=en</S.A>.</li>
            </S.UL>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Links to Other Sites</S.H2>
            <S.P>
            Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.
            </S.P>
            <S.P>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </S.P>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Children’s Privacy</S.H2>
            <S.P>
            Our Service does not address anyone under the age of 18 (“Children”).
            </S.P>
            <S.P>
            We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
            </S.P>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Changes to This Privacy Policy</S.H2>
            <S.P>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            </S.P>
            <S.P>
            We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy.
            </S.P>
            <S.P>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </S.P>
          </S.StyledDiv>

          <S.StyledDiv>
              <S.H2>Contact Us</S.H2>
            <S.P>
            If you have any questions about this Privacy Policy, please contact us:
            </S.P>
            <S.UL>
                <li>By email: info@hempup.com</li>
   
            </S.UL>
          </S.StyledDiv>
          

        </S.StyledArticle>
      </S.Wrapper>
    </>
  )
}
export default Privacy
